use super::{ReasoningCapability, cost, model, runtime};
use crate::registry::{ApiType, Model};

pub(super) fn builtin_models() -> Vec<Model> {
    vec![
        model(
            "claude-sonnet-4-6",
            "Claude Sonnet 4.6",
            "anthropic",
            ApiType::AnthropicMessages,
            (1_000_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-opus-4-6",
            "Claude Opus 4.6",
            "anthropic",
            ApiType::AnthropicMessages,
            (1_000_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(5.0, 25.0, 0.5, 6.25),
        ),
        model(
            "claude-sonnet-4-20250514",
            "Claude Sonnet 4",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-opus-4-20250514",
            "Claude Opus 4",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 32_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(15.0, 75.0, 1.5, 18.75),
        ),
        model(
            "claude-haiku-4-5-20251001",
            "Claude Haiku 4.5",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(0.8, 4.0, 0.08, 1.0),
        ),
        model(
            "claude-haiku-4-20260115",
            "Claude Haiku 4",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(0.5, 2.5, 0.05, 0.625),
        ),
        model(
            "claude-sonnet-4-20260115",
            "Claude Sonnet 4 (Jan 2026)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-opus-4-20260115",
            "Claude Opus 4 (Jan 2026)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 32_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(15.0, 75.0, 1.5, 18.75),
        ),
        model(
            "claude-3-5-haiku-20241022",
            "Claude 3.5 Haiku",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.anthropic.com",
            ),
            cost(0.8, 4.0, 0.08, 1.0),
        ),
        model(
            "claude-3-7-sonnet-20250219",
            "Claude 3.7 Sonnet",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
    ]
}
