use super::{ReasoningCapability, cost, model, runtime};
use crate::registry::{ApiType, Model};

pub(super) fn builtin_models() -> Vec<Model> {
    vec![
        model(
            "claude-3-5-haiku-20241022",
            "Claude Haiku 3.5",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.anthropic.com",
            ),
            cost(0.8, 4.0, 0.08, 1.0),
        ),
        model(
            "claude-3-5-haiku-latest",
            "Claude Haiku 3.5 (latest)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.anthropic.com",
            ),
            cost(0.8, 4.0, 0.08, 1.0),
        ),
        model(
            "claude-3-5-sonnet-20240620",
            "Claude Sonnet 3.5",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.anthropic.com",
            ),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-3-5-sonnet-20241022",
            "Claude Sonnet 3.5 v2",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.anthropic.com",
            ),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-3-7-sonnet-20250219",
            "Claude Sonnet 3.7",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-3-haiku-20240307",
            "Claude Haiku 3",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 4_096),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.anthropic.com",
            ),
            cost(0.25, 1.25, 0.03, 0.3),
        ),
        model(
            "claude-3-opus-20240229",
            "Claude Opus 3",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 4_096),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.anthropic.com",
            ),
            cost(15.0, 75.0, 1.5, 18.75),
        ),
        model(
            "claude-3-sonnet-20240229",
            "Claude Sonnet 3",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 4_096),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.anthropic.com",
            ),
            cost(3.0, 15.0, 0.3, 0.3),
        ),
        model(
            "claude-haiku-4-5",
            "Claude Haiku 4.5 (latest)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(1.0, 5.0, 0.1, 1.25),
        ),
        model(
            "claude-haiku-4-5-20251001",
            "Claude Haiku 4.5",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(1.0, 5.0, 0.1, 1.25),
        ),
        model(
            "claude-opus-4-0",
            "Claude Opus 4 (latest)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 32_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(15.0, 75.0, 1.5, 18.75),
        ),
        model(
            "claude-opus-4-1",
            "Claude Opus 4.1 (latest)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 32_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(15.0, 75.0, 1.5, 18.75),
        ),
        model(
            "claude-opus-4-1-20250805",
            "Claude Opus 4.1",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 32_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(15.0, 75.0, 1.5, 18.75),
        ),
        model(
            "claude-opus-4-20250514",
            "Claude Opus 4",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 32_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(15.0, 75.0, 1.5, 18.75),
        ),
        model(
            "claude-opus-4-5",
            "Claude Opus 4.5 (latest)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(5.0, 25.0, 0.5, 6.25),
        ),
        model(
            "claude-opus-4-5-20251101",
            "Claude Opus 4.5",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(5.0, 25.0, 0.5, 6.25),
        ),
        model(
            "claude-opus-4-6",
            "Claude Opus 4.6",
            "anthropic",
            ApiType::AnthropicMessages,
            (1_000_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(5.0, 25.0, 0.5, 6.25),
        ),
        model(
            "claude-opus-4-7",
            "Claude Opus 4.7",
            "anthropic",
            ApiType::AnthropicMessages,
            (1_000_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(5.0, 25.0, 0.5, 6.25),
        ),
        model(
            "claude-sonnet-4-0",
            "Claude Sonnet 4 (latest)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-sonnet-4-20250514",
            "Claude Sonnet 4",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-sonnet-4-5",
            "Claude Sonnet 4.5 (latest)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-sonnet-4-5-20250929",
            "Claude Sonnet 4.5",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-sonnet-4-6",
            "Claude Sonnet 4.6",
            "anthropic",
            ApiType::AnthropicMessages,
            (1_000_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        // Preserved BB-Agent-specific aliases.
        model(
            "claude-haiku-4-20260115",
            "Claude Haiku 4",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(0.5, 2.5, 0.05, 0.625),
        ),
        model(
            "claude-sonnet-4-20260115",
            "Claude Sonnet 4 (Jan 2026)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 64_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(3.0, 15.0, 0.3, 3.75),
        ),
        model(
            "claude-opus-4-20260115",
            "Claude Opus 4 (Jan 2026)",
            "anthropic",
            ApiType::AnthropicMessages,
            (200_000, 32_000),
            runtime(ReasoningCapability::Supported, "https://api.anthropic.com"),
            cost(15.0, 75.0, 1.5, 18.75),
        ),
    ]
}
