use super::{ReasoningCapability, model, runtime, simple_cost};
use crate::registry::{ApiType, Model};

pub(super) fn builtin_models() -> Vec<Model> {
    vec![
        model(
            "claude-haiku-4.5",
            "Claude Haiku 4.5",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (144_000, 32_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "claude-opus-4.5",
            "Claude Opus 4.5",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (160_000, 32_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "claude-opus-4.6",
            "Claude Opus 4.6",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (1_000_000, 64_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "claude-opus-4.7",
            "Claude Opus 4.7",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (144_000, 64_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "claude-sonnet-4",
            "Claude Sonnet 4",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (216_000, 16_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "claude-sonnet-4.5",
            "Claude Sonnet 4.5",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (216_000, 32_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "claude-sonnet-4.6",
            "Claude Sonnet 4.6",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (216_000, 64_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gemini-2.5-pro",
            "Gemini 2.5 Pro",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gemini-3-flash-preview",
            "Gemini 3 Flash Preview",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gemini-3-pro-preview",
            "Gemini 3 Pro Preview",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (1_000_000, 64_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gemini-3.1-pro-preview",
            "Gemini 3.1 Pro Preview",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-4.1",
            "GPT-4.1",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (1_047_576, 32_768),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-4o",
            "GPT-4o",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (128_000, 16_384),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5",
            "GPT-5",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5-mini",
            "GPT-5 Mini",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.1",
            "GPT-5.1",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.1-codex",
            "GPT-5.1 Codex",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.1-codex-max",
            "GPT-5.1 Codex Max",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.1-codex-mini",
            "GPT-5.1 Codex mini",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.2",
            "GPT-5.2",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.2-codex",
            "GPT-5.2 Codex",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.3-codex",
            "GPT-5.3 Codex",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.4",
            "GPT-5.4",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (272_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.4-mini",
            "GPT-5.4 mini",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "gpt-5.5",
            "GPT-5.5",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (272_000, 128_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        model(
            "grok-code-fast-1",
            "Grok Code Fast 1",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (256_000, 32_768),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
        // Preserved BB-Agent alias.
        model(
            "o3-mini",
            "o3-mini (Copilot)",
            "github-copilot",
            ApiType::OpenaiCompletions,
            (200_000, 100_000),
            runtime(
                ReasoningCapability::Supported,
                "https://api.individual.githubcopilot.com",
            ),
            simple_cost(0.0, 0.0),
        ),
    ]
}
