use super::{ReasoningCapability, model, runtime, simple_cost, text_model};
use crate::registry::{ApiType, Model};

pub(super) fn builtin_models() -> Vec<Model> {
    vec![
        model(
            "gemini-1.5-flash",
            "Gemini 1.5 Flash",
            "google",
            ApiType::GoogleGenerative,
            (1_000_000, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.075, 0.3),
        ),
        model(
            "gemini-1.5-flash-8b",
            "Gemini 1.5 Flash-8B",
            "google",
            ApiType::GoogleGenerative,
            (1_000_000, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.0375, 0.15),
        ),
        model(
            "gemini-1.5-pro",
            "Gemini 1.5 Pro",
            "google",
            ApiType::GoogleGenerative,
            (1_000_000, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(1.25, 5.0),
        ),
        model(
            "gemini-2.0-flash",
            "Gemini 2.0 Flash",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.1, 0.4),
        ),
        model(
            "gemini-2.0-flash-lite",
            "Gemini 2.0 Flash Lite",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.075, 0.3),
        ),
        model(
            "gemini-2.5-flash",
            "Gemini 2.5 Flash",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.15, 0.6),
        ),
        model(
            "gemini-2.5-flash-lite",
            "Gemini 2.5 Flash Lite",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.075, 0.3),
        ),
        model(
            "gemini-2.5-flash-lite-preview-06-17",
            "Gemini 2.5 Flash Lite Preview 06-17",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.075, 0.3),
        ),
        model(
            "gemini-2.5-flash-lite-preview-09-2025",
            "Gemini 2.5 Flash Lite Preview 09-25",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.075, 0.3),
        ),
        model(
            "gemini-2.5-flash-preview-04-17",
            "Gemini 2.5 Flash Preview 04-17",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.15, 0.6),
        ),
        model(
            "gemini-2.5-flash-preview-05-20",
            "Gemini 2.5 Flash Preview 05-20",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.15, 0.6),
        ),
        model(
            "gemini-2.5-flash-preview-09-2025",
            "Gemini 2.5 Flash Preview 09-25",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.15, 0.6),
        ),
        model(
            "gemini-2.5-pro",
            "Gemini 2.5 Pro",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gemini-2.5-pro-preview-05-06",
            "Gemini 2.5 Pro Preview 05-06",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gemini-2.5-pro-preview-06-05",
            "Gemini 2.5 Pro Preview 06-05",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gemini-3-flash-preview",
            "Gemini 3 Flash Preview",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.2, 0.8),
        ),
        model(
            "gemini-3-pro-preview",
            "Gemini 3 Pro Preview",
            "google",
            ApiType::GoogleGenerative,
            (1_000_000, 64_000),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(1.5, 12.0),
        ),
        model(
            "gemini-3.1-flash-lite-preview",
            "Gemini 3.1 Flash Lite Preview",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.1, 0.4),
        ),
        model(
            "gemini-3.1-pro-preview",
            "Gemini 3.1 Pro Preview",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gemini-3.1-pro-preview-customtools",
            "Gemini 3.1 Pro Preview Custom Tools",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gemini-flash-latest",
            "Gemini Flash Latest",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.15, 0.6),
        ),
        model(
            "gemini-flash-lite-latest",
            "Gemini Flash-Lite Latest",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.075, 0.3),
        ),
        model(
            "gemini-live-2.5-flash",
            "Gemini Live 2.5 Flash",
            "google",
            ApiType::GoogleGenerative,
            (128_000, 8_000),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.15, 0.6),
        ),
        text_model(
            "gemini-live-2.5-flash-preview-native-audio",
            "Gemini Live 2.5 Flash Preview Native Audio",
            "google",
            ApiType::GoogleGenerative,
            (131_072, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.15, 0.6),
        ),
        model(
            "gemma-3-27b-it",
            "Gemma 3 27B",
            "google",
            ApiType::GoogleGenerative,
            (131_072, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.15, 0.6),
        ),
        model(
            "gemma-4-26b-a4b-it",
            "Gemma 4 26B",
            "google",
            ApiType::GoogleGenerative,
            (256_000, 8_192),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.2, 0.8),
        ),
        model(
            "gemma-4-31b-it",
            "Gemma 4 31B",
            "google",
            ApiType::GoogleGenerative,
            (256_000, 8_192),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(0.2, 0.8),
        ),
        // Preserved BB-Agent alias for compatibility.
        model(
            "gemini-3.1-pro",
            "Gemini 3.1 Pro",
            "google",
            ApiType::GoogleGenerative,
            (1_048_576, 65_536),
            runtime(
                ReasoningCapability::Supported,
                "https://generativelanguage.googleapis.com/v1beta",
            ),
            simple_cost(1.25, 10.0),
        ),
    ]
}
