use super::{ReasoningCapability, model, runtime, simple_cost, text_model};
use crate::registry::{ApiType, Model};

pub(super) fn builtin_models() -> Vec<Model> {
    vec![
        text_model(
            "deepseek-r1-distill-llama-70b",
            "DeepSeek R1 Distill Llama 70B",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 8_192),
            runtime(ReasoningCapability::Supported, "https://api.groq.com/openai/v1"),
            simple_cost(0.75, 0.99),
        ),
        text_model(
            "gemma2-9b-it",
            "Gemma 2 9B",
            "groq",
            ApiType::OpenaiCompletions,
            (8_192, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.2, 0.2),
        ),
        text_model(
            "groq/compound",
            "Compound",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 8_192),
            runtime(ReasoningCapability::Supported, "https://api.groq.com/openai/v1"),
            simple_cost(0.59, 0.79),
        ),
        text_model(
            "groq/compound-mini",
            "Compound Mini",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 8_192),
            runtime(ReasoningCapability::Supported, "https://api.groq.com/openai/v1"),
            simple_cost(0.19, 0.29),
        ),
        text_model(
            "llama-3.1-8b-instant",
            "Llama 3.1 8B Instant",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 131_072),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.05, 0.08),
        ),
        text_model(
            "llama-3.3-70b-versatile",
            "Llama 3.3 70B Versatile",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 32_768),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.59, 0.79),
        ),
        text_model(
            "llama3-70b-8192",
            "Llama 3 70B",
            "groq",
            ApiType::OpenaiCompletions,
            (8_192, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.59, 0.79),
        ),
        text_model(
            "llama3-8b-8192",
            "Llama 3 8B",
            "groq",
            ApiType::OpenaiCompletions,
            (8_192, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.05, 0.08),
        ),
        model(
            "meta-llama/llama-4-maverick-17b-128e-instruct",
            "Llama 4 Maverick 17B",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.29, 0.59),
        ),
        model(
            "meta-llama/llama-4-scout-17b-16e-instruct",
            "Llama 4 Scout 17B",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.19, 0.39),
        ),
        text_model(
            "mistral-saba-24b",
            "Mistral Saba 24B",
            "groq",
            ApiType::OpenaiCompletions,
            (32_768, 32_768),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.24, 0.24),
        ),
        text_model(
            "moonshotai/kimi-k2-instruct",
            "Kimi K2 Instruct",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 16_384),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.4, 1.6),
        ),
        text_model(
            "moonshotai/kimi-k2-instruct-0905",
            "Kimi K2 Instruct 0905",
            "groq",
            ApiType::OpenaiCompletions,
            (262_144, 16_384),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.4, 1.6),
        ),
        text_model(
            "openai/gpt-oss-120b",
            "GPT OSS 120B",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 65_536),
            runtime(ReasoningCapability::Supported, "https://api.groq.com/openai/v1"),
            simple_cost(0.15, 0.6),
        ),
        text_model(
            "openai/gpt-oss-20b",
            "GPT OSS 20B",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 65_536),
            runtime(ReasoningCapability::Supported, "https://api.groq.com/openai/v1"),
            simple_cost(0.1, 0.3),
        ),
        text_model(
            "openai/gpt-oss-safeguard-20b",
            "Safety GPT OSS 20B",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 65_536),
            runtime(ReasoningCapability::Supported, "https://api.groq.com/openai/v1"),
            simple_cost(0.1, 0.2),
        ),
        text_model(
            "qwen-qwq-32b",
            "Qwen QwQ 32B",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 16_384),
            runtime(ReasoningCapability::Supported, "https://api.groq.com/openai/v1"),
            simple_cost(0.29, 0.59),
        ),
        text_model(
            "qwen/qwen3-32b",
            "Qwen3 32B",
            "groq",
            ApiType::OpenaiCompletions,
            (131_072, 40_960),
            runtime(ReasoningCapability::Supported, "https://api.groq.com/openai/v1"),
            simple_cost(0.29, 0.59),
        ),
        // Preserved BB-Agent entry.
        text_model(
            "mixtral-8x7b-32768",
            "Mixtral 8x7B",
            "groq",
            ApiType::OpenaiCompletions,
            (32_768, 32_768),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.groq.com/openai/v1",
            ),
            simple_cost(0.24, 0.24),
        ),
    ]
}
