use super::{ReasoningCapability, model, runtime, simple_cost, text_model};
use crate::registry::{ApiType, Model};

pub(super) fn builtin_models() -> Vec<Model> {
    vec![
        text_model(
            "gpt-4",
            "GPT-4",
            "openai",
            ApiType::OpenaiResponses,
            (8_192, 8_192),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(30.0, 60.0),
        ),
        model(
            "gpt-4-turbo",
            "GPT-4 Turbo",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 4_096),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(10.0, 30.0),
        ),
        model(
            "gpt-4.1",
            "GPT-4.1",
            "openai",
            ApiType::OpenaiResponses,
            (1_047_576, 32_768),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(2.0, 8.0),
        ),
        model(
            "gpt-4.1-mini",
            "GPT-4.1 mini",
            "openai",
            ApiType::OpenaiResponses,
            (1_047_576, 32_768),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(0.4, 1.6),
        ),
        model(
            "gpt-4.1-nano",
            "GPT-4.1 nano",
            "openai",
            ApiType::OpenaiResponses,
            (1_047_576, 32_768),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(0.1, 0.4),
        ),
        model(
            "gpt-4o",
            "GPT-4o",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 16_384),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(2.5, 10.0),
        ),
        model(
            "gpt-4o-2024-05-13",
            "GPT-4o (2024-05-13)",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 4_096),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(5.0, 15.0),
        ),
        model(
            "gpt-4o-2024-08-06",
            "GPT-4o (2024-08-06)",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 16_384),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(2.5, 10.0),
        ),
        model(
            "gpt-4o-2024-11-20",
            "GPT-4o (2024-11-20)",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 16_384),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(2.5, 10.0),
        ),
        model(
            "gpt-4o-mini",
            "GPT-4o mini",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 16_384),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(0.15, 0.6),
        ),
        model(
            "gpt-5",
            "GPT-5",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gpt-5-chat-latest",
            "GPT-5 Chat Latest",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 16_384),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gpt-5-codex",
            "GPT-5-Codex",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gpt-5-mini",
            "GPT-5 Mini",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(0.25, 2.0),
        ),
        model(
            "gpt-5-nano",
            "GPT-5 Nano",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(0.05, 0.4),
        ),
        model(
            "gpt-5-pro",
            "GPT-5 Pro",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 272_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(15.0, 120.0),
        ),
        model(
            "gpt-5.1",
            "GPT-5.1",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gpt-5.1-chat-latest",
            "GPT-5.1 Chat",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 16_384),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gpt-5.1-codex",
            "GPT-5.1 Codex",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gpt-5.1-codex-max",
            "GPT-5.1 Codex Max",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.25, 10.0),
        ),
        model(
            "gpt-5.1-codex-mini",
            "GPT-5.1 Codex mini",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(0.25, 2.0),
        ),
        model(
            "gpt-5.2",
            "GPT-5.2",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.75, 14.0),
        ),
        model(
            "gpt-5.2-chat-latest",
            "GPT-5.2 Chat",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 16_384),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.75, 14.0),
        ),
        model(
            "gpt-5.2-codex",
            "GPT-5.2 Codex",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.75, 14.0),
        ),
        model(
            "gpt-5.2-pro",
            "GPT-5.2 Pro",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(21.0, 168.0),
        ),
        model(
            "gpt-5.3-chat-latest",
            "GPT-5.3 Chat (latest)",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 16_384),
            runtime(
                ReasoningCapability::Unsupported,
                "https://api.openai.com/v1",
            ),
            simple_cost(1.75, 14.0),
        ),
        model(
            "gpt-5.3-codex",
            "GPT-5.3 Codex",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.75, 14.0),
        ),
        model(
            "gpt-5.3-codex-spark",
            "GPT-5.3 Codex Spark",
            "openai",
            ApiType::OpenaiResponses,
            (128_000, 32_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.75, 14.0),
        ),
        model(
            "gpt-5.4",
            "GPT-5.4",
            "openai",
            ApiType::OpenaiResponses,
            (272_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(2.5, 15.0),
        ),
        model(
            "gpt-5.4-mini",
            "GPT-5.4 mini",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(0.75, 4.5),
        ),
        model(
            "gpt-5.4-nano",
            "GPT-5.4 nano",
            "openai",
            ApiType::OpenaiResponses,
            (400_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(0.2, 1.25),
        ),
        model(
            "gpt-5.4-pro",
            "GPT-5.4 Pro",
            "openai",
            ApiType::OpenaiResponses,
            (1_050_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(30.0, 180.0),
        ),
        model(
            "gpt-5.5",
            "GPT-5.5",
            "openai",
            ApiType::OpenaiResponses,
            (272_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(5.0, 30.0),
        ),
        model(
            "gpt-5.5-pro",
            "GPT-5.5 Pro",
            "openai",
            ApiType::OpenaiResponses,
            (1_050_000, 128_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(30.0, 180.0),
        ),
        model(
            "o1",
            "o1",
            "openai",
            ApiType::OpenaiResponses,
            (200_000, 100_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(15.0, 60.0),
        ),
        model(
            "o1-pro",
            "o1-pro",
            "openai",
            ApiType::OpenaiResponses,
            (200_000, 100_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(150.0, 600.0),
        ),
        model(
            "o3",
            "o3",
            "openai",
            ApiType::OpenaiResponses,
            (200_000, 100_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(2.0, 8.0),
        ),
        model(
            "o3-deep-research",
            "o3-deep-research",
            "openai",
            ApiType::OpenaiResponses,
            (200_000, 100_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(10.0, 40.0),
        ),
        text_model(
            "o3-mini",
            "o3-mini",
            "openai",
            ApiType::OpenaiResponses,
            (200_000, 100_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.1, 4.4),
        ),
        model(
            "o3-pro",
            "o3-pro",
            "openai",
            ApiType::OpenaiResponses,
            (200_000, 100_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(20.0, 80.0),
        ),
        model(
            "o4-mini",
            "o4-mini",
            "openai",
            ApiType::OpenaiResponses,
            (200_000, 100_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(1.1, 4.4),
        ),
        model(
            "o4-mini-deep-research",
            "o4-mini-deep-research",
            "openai",
            ApiType::OpenaiResponses,
            (200_000, 100_000),
            runtime(ReasoningCapability::Supported, "https://api.openai.com/v1"),
            simple_cost(2.0, 8.0),
        ),
    ]
}
