use super::{model, runtime, simple_cost};
use crate::registry::{ApiType, Model};

pub(super) fn builtin_models() -> Vec<Model> {
    vec![
        model(
            "gpt-5.4",
            "GPT-5.4",
            "openai",
            ApiType::OpenaiCompletions,
            (272_000, 128_000),
            runtime(true, "https://api.openai.com/v1"),
            simple_cost(2.5, 10.0),
        ),
        model(
            "gpt-5.2",
            "GPT-5.2",
            "openai",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(true, "https://api.openai.com/v1"),
            simple_cost(2.0, 8.0),
        ),
        model(
            "gpt-5.1-codex",
            "GPT-5.1 Codex",
            "openai",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(true, "https://api.openai.com/v1"),
            simple_cost(2.0, 8.0),
        ),
        model(
            "gpt-5",
            "GPT-5",
            "openai",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(true, "https://api.openai.com/v1"),
            simple_cost(2.0, 8.0),
        ),
        model(
            "gpt-5-mini",
            "GPT-5 Mini",
            "openai",
            ApiType::OpenaiCompletions,
            (400_000, 128_000),
            runtime(true, "https://api.openai.com/v1"),
            simple_cost(0.3, 1.2),
        ),
        model(
            "gpt-4o",
            "GPT-4o",
            "openai",
            ApiType::OpenaiCompletions,
            (128_000, 16_384),
            runtime(false, "https://api.openai.com/v1"),
            simple_cost(2.5, 10.0),
        ),
        model(
            "gpt-4o-mini",
            "GPT-4o Mini",
            "openai",
            ApiType::OpenaiCompletions,
            (128_000, 16_384),
            runtime(false, "https://api.openai.com/v1"),
            simple_cost(0.15, 0.6),
        ),
        model(
            "o3",
            "o3",
            "openai",
            ApiType::OpenaiCompletions,
            (200_000, 100_000),
            runtime(true, "https://api.openai.com/v1"),
            simple_cost(2.0, 8.0),
        ),
        model(
            "o3-mini",
            "o3-mini",
            "openai",
            ApiType::OpenaiCompletions,
            (200_000, 100_000),
            runtime(true, "https://api.openai.com/v1"),
            simple_cost(1.1, 4.4),
        ),
        model(
            "o4-mini",
            "o4-mini",
            "openai",
            ApiType::OpenaiCompletions,
            (200_000, 100_000),
            runtime(true, "https://api.openai.com/v1"),
            simple_cost(1.1, 4.4),
        ),
        model(
            "gpt-4-turbo",
            "GPT-4 Turbo",
            "openai",
            ApiType::OpenaiCompletions,
            (128_000, 4_096),
            runtime(false, "https://api.openai.com/v1"),
            simple_cost(10.0, 30.0),
        ),
        model(
            "o1-mini",
            "o1-mini",
            "openai",
            ApiType::OpenaiCompletions,
            (128_000, 65_536),
            runtime(true, "https://api.openai.com/v1"),
            simple_cost(3.0, 12.0),
        ),
    ]
}
